/***********************************************************************/
/*                                                                     */
/*  FILE        :lcd_c_lang.c                                          */
/*  DATE        :Fri, Nov 06, 2020                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3062F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
